/* The following code was generated by JFlex 1.6.1 */

/*
    Tiger.flex

    Lexical specification file for Andrew Appel's Tiger language.

    Author:  John Lasseter

    History:
        09/01/2011 (jhel): created
        02/13/2014 (jhel): added peek() method to code section
        02/19/2014 (jhel): fixed peek()
        02/29/2016 (jhel): fixed the constructor call
        04/25/2018 (jhel):  fixed a subtle bug in handling of escape codes
*/

package tigerc.syntax.parse;
import java.io.IOException;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>/Users/jlasseter/Documents/work/software/teaching/Compilers/TigerC (full)/src/tigerc/syntax/parse/Tiger.flex</tt>
 */
public class TigerLex implements Lexer, java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int COMMENT = 2;
  public static final int STRING = 4;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2, 2
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\6\1\10\1\61\1\61\1\7\22\0\1\6\1\0\1\5"+
    "\3\0\1\57\1\0\1\47\1\50\1\24\1\56\1\45\1\22\1\55"+
    "\1\23\12\2\1\42\1\46\1\21\1\43\1\44\2\0\32\1\1\51"+
    "\1\4\1\52\1\0\1\3\1\0\1\17\1\15\1\36\1\34\1\14"+
    "\1\33\1\1\1\32\1\12\1\1\1\20\1\11\1\25\1\13\1\27"+
    "\1\26\1\1\1\16\1\41\1\30\1\35\1\37\1\31\1\1\1\40"+
    "\1\1\1\53\1\60\1\54\7\0\1\61\u1fa2\0\1\61\1\61\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\3\0\1\1\1\2\1\3\1\4\1\5\2\6\6\2"+
    "\1\7\1\10\1\11\1\12\6\2\1\13\1\14\1\15"+
    "\1\16\1\17\1\20\1\21\1\22\1\23\1\24\1\25"+
    "\1\26\1\27\1\30\1\31\3\32\2\33\1\34\2\35"+
    "\1\2\1\36\1\2\1\37\5\2\1\0\1\40\1\41"+
    "\1\42\1\43\1\44\5\2\1\45\1\2\1\46\1\47"+
    "\1\50\1\51\2\52\1\53\1\54\1\52\1\0\1\52"+
    "\1\55\1\56\1\57\1\2\1\60\1\2\1\61\2\2"+
    "\1\62\3\2\1\63\1\2\1\64\3\0\1\65\1\2"+
    "\1\66\2\2\1\67\1\70\2\2\1\0\1\2\1\71"+
    "\1\72\1\73\1\2\1\74\1\75\2\2\1\76";

  private static int [] zzUnpackAction() {
    int [] result = new int[121];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\62\0\144\0\226\0\310\0\372\0\226\0\226"+
    "\0\u012c\0\226\0\u015e\0\u0190\0\u01c2\0\u01f4\0\u0226\0\u0258"+
    "\0\u028a\0\226\0\u02bc\0\226\0\u02ee\0\u0320\0\u0352\0\u0384"+
    "\0\u03b6\0\u03e8\0\u041a\0\226\0\u044c\0\226\0\226\0\226"+
    "\0\226\0\226\0\226\0\226\0\226\0\226\0\226\0\226"+
    "\0\226\0\226\0\u047e\0\u04b0\0\226\0\u04e2\0\226\0\u0514"+
    "\0\226\0\u0546\0\310\0\u0578\0\310\0\u05aa\0\u05dc\0\u060e"+
    "\0\u0640\0\u0672\0\u06a4\0\226\0\226\0\226\0\310\0\310"+
    "\0\u06d6\0\u0708\0\u073a\0\u076c\0\u079e\0\310\0\u07d0\0\226"+
    "\0\226\0\226\0\226\0\226\0\u0802\0\226\0\226\0\u0834"+
    "\0\u0866\0\u0898\0\226\0\226\0\310\0\u08ca\0\310\0\u08fc"+
    "\0\310\0\u092e\0\u0960\0\226\0\u0992\0\u09c4\0\u09f6\0\310"+
    "\0\u0a28\0\310\0\u0a5a\0\u0834\0\u0898\0\226\0\u0a8c\0\310"+
    "\0\u0abe\0\u0af0\0\310\0\310\0\u0b22\0\u0b54\0\u0b86\0\u0bb8"+
    "\0\310\0\310\0\310\0\u0bea\0\226\0\310\0\u0c1c\0\u0c4e"+
    "\0\310";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[121];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\4\1\5\1\6\2\4\1\7\1\10\1\11\1\12"+
    "\1\13\1\14\1\15\1\16\1\17\1\5\1\20\1\5"+
    "\1\21\1\22\1\23\1\24\2\5\1\25\1\26\1\27"+
    "\1\5\1\30\1\31\2\5\1\32\2\5\1\33\1\34"+
    "\1\35\1\36\1\37\1\40\1\41\1\42\1\43\1\44"+
    "\1\45\1\46\1\47\1\50\1\51\1\0\7\52\1\11"+
    "\1\12\12\52\1\53\1\54\34\52\1\0\4\55\1\56"+
    "\1\57\1\55\1\60\1\61\50\55\64\0\3\5\5\0"+
    "\10\5\4\0\15\5\22\0\1\6\67\0\1\12\52\0"+
    "\3\5\5\0\3\5\1\62\4\5\4\0\15\5\21\0"+
    "\3\5\5\0\2\5\1\63\5\5\4\0\1\64\5\5"+
    "\1\65\6\5\21\0\3\5\5\0\1\5\1\66\6\5"+
    "\4\0\15\5\21\0\3\5\5\0\1\67\1\5\1\70"+
    "\5\5\4\0\15\5\21\0\3\5\5\0\5\5\1\71"+
    "\2\5\4\0\15\5\21\0\3\5\5\0\5\5\1\72"+
    "\2\5\4\0\15\5\42\0\1\73\20\0\1\74\1\75"+
    "\41\0\1\76\36\0\3\5\5\0\10\5\4\0\6\5"+
    "\1\77\6\5\21\0\3\5\5\0\10\5\4\0\2\5"+
    "\1\100\2\5\1\101\5\5\1\102\1\5\21\0\3\5"+
    "\5\0\10\5\4\0\5\5\1\103\7\5\21\0\3\5"+
    "\5\0\10\5\4\0\2\5\1\104\5\5\1\105\4\5"+
    "\21\0\3\5\5\0\10\5\4\0\2\5\1\106\12\5"+
    "\21\0\3\5\5\0\6\5\1\107\1\5\4\0\15\5"+
    "\63\0\1\110\61\0\1\111\42\0\1\112\60\0\1\113"+
    "\36\0\2\114\1\115\1\114\1\116\1\117\1\120\1\121"+
    "\1\122\2\114\1\123\14\114\1\124\30\114\11\0\1\61"+
    "\52\0\3\5\5\0\10\5\4\0\3\5\1\125\11\5"+
    "\21\0\3\5\5\0\10\5\4\0\1\5\1\126\13\5"+
    "\21\0\3\5\5\0\1\127\7\5\4\0\15\5\21\0"+
    "\3\5\5\0\10\5\4\0\14\5\1\130\21\0\3\5"+
    "\5\0\10\5\4\0\7\5\1\131\5\5\21\0\3\5"+
    "\5\0\3\5\1\132\4\5\4\0\15\5\21\0\3\5"+
    "\5\0\5\5\1\133\2\5\4\0\15\5\42\0\1\134"+
    "\40\0\3\5\5\0\3\5\1\135\4\5\4\0\15\5"+
    "\21\0\3\5\5\0\10\5\4\0\1\5\1\136\13\5"+
    "\21\0\3\5\5\0\1\5\1\137\6\5\4\0\15\5"+
    "\21\0\3\5\5\0\5\5\1\140\2\5\4\0\15\5"+
    "\21\0\3\5\5\0\2\5\1\141\5\5\4\0\15\5"+
    "\21\0\3\5\5\0\5\5\1\142\2\5\4\0\15\5"+
    "\22\0\1\143\65\0\1\144\1\121\1\145\55\0\1\146"+
    "\1\0\1\145\1\0\1\145\55\0\1\146\1\0\1\145"+
    "\54\0\3\5\5\0\10\5\4\0\2\5\1\147\12\5"+
    "\21\0\3\5\5\0\3\5\1\150\4\5\4\0\15\5"+
    "\21\0\3\5\5\0\6\5\1\151\1\5\4\0\15\5"+
    "\21\0\3\5\5\0\6\5\1\152\1\5\4\0\15\5"+
    "\21\0\3\5\5\0\2\5\1\153\5\5\4\0\15\5"+
    "\21\0\3\5\5\0\3\5\1\154\4\5\4\0\15\5"+
    "\21\0\3\5\5\0\1\155\7\5\4\0\15\5\21\0"+
    "\3\5\5\0\10\5\4\0\11\5\1\156\3\5\22\0"+
    "\1\157\60\0\3\5\5\0\5\5\1\160\2\5\4\0"+
    "\15\5\21\0\3\5\5\0\7\5\1\161\4\0\15\5"+
    "\21\0\3\5\5\0\10\5\4\0\13\5\1\162\1\5"+
    "\21\0\3\5\5\0\3\5\1\163\4\5\4\0\15\5"+
    "\21\0\3\5\5\0\10\5\4\0\3\5\1\164\11\5"+
    "\26\0\1\165\54\0\3\5\5\0\10\5\4\0\3\5"+
    "\1\166\11\5\21\0\3\5\5\0\1\5\1\167\6\5"+
    "\4\0\15\5\21\0\3\5\5\0\10\5\4\0\2\5"+
    "\1\170\12\5\21\0\3\5\5\0\2\5\1\171\5\5"+
    "\4\0\15\5\20\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[3200];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\3\0\1\11\2\1\2\11\1\1\1\11\7\1\1\11"+
    "\1\1\1\11\7\1\1\11\1\1\15\11\2\1\1\11"+
    "\1\1\1\11\1\1\1\11\11\1\1\0\3\11\11\1"+
    "\5\11\1\1\2\11\1\1\1\0\1\1\2\11\7\1"+
    "\1\11\6\1\3\0\1\11\10\1\1\0\5\1\1\11"+
    "\4\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[121];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
    private tigerc.util.ErrorMsg errorMsg;
    private int commentDepth = 0;
    private int commentOrStringBegins = -1;
    private boolean readingString = false;
    private String currentString;

    private int charsReadForStr = 0;

    public TigerLex(java.io.InputStream s, tigerc.util.ErrorMsg e) {
        this(new java.io.InputStreamReader(new java.io.BufferedInputStream(s)));
        this.errorMsg=e;
    }

	public TigerLex(java.io.Reader r, tigerc.util.ErrorMsg e) {
	    this(r);
		this.errorMsg = e;
	}

    private void newline() { errorMsg.newline(); }

    private void err (String s) { err(yycolumn,s); }
    private void err (int pos, String s) { errorMsg.error(pos,s); }


    private java_cup.runtime.Symbol tok (int kind) { return tok(kind, null); }
    private java_cup.runtime.Symbol tok (int kind, Object value) {
        // Uncomment the following line, if you want a debugging message:
    	//System.err.println("LEX: " + yytext() + "[" + yychar + ","+ (yychar+yylength()) +"]"  );

        return new java_cup.runtime.Symbol(kind, yychar, yychar+yylength(), value);
    }

    public java_cup.runtime.Symbol peek() throws java.io.IOException {
        java_cup.runtime.Symbol sym = this.next_token();

        if (sym.sym == TigerSyms.STRING) {
            zzStartRead -= (charsReadForStr + 1);
		}
        yypushback(yylength());
        return sym;
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public TigerLex(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 172) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException, IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { // Code to go in the lexical analyzer class; to be executed when eof is
// reached
  {
    if (commentDepth != 0) {
      err("Unclosed comment detected at end of file "
	  + "(begins on line " + commentOrStringBegins + ").");
    }
    else if (readingString) {
      err("Unclosed string detected at end of file "
	  + "(begins on line " + commentOrStringBegins + ").");
    }

     return tok(TigerSyms.EOF);
  }
 }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { // Handling of bogus input
  char c = yytext().charAt(0);
  if (! Character.isWhitespace(c))
    err("Ignoring unknown character " + c + " at line " + yyline);
            }
          case 63: break;
          case 2: 
            { return tok(TigerSyms.ID, yytext());
            }
          case 64: break;
          case 3: 
            { return tok(TigerSyms.INT, new Integer(yytext()));
            }
          case 65: break;
          case 4: 
            { currentString = new String();
  readingString = true;
  commentOrStringBegins = yyline;
  charsReadForStr = 0;
  yybegin(STRING);
            }
          case 66: break;
          case 5: 
            { 
            }
          case 67: break;
          case 6: 
            { newline();
            }
          case 68: break;
          case 7: 
            { return tok(TigerSyms.LT);
            }
          case 69: break;
          case 8: 
            { return tok(TigerSyms.MINUS);
            }
          case 70: break;
          case 9: 
            { return tok(TigerSyms.DIVIDE);
            }
          case 71: break;
          case 10: 
            { return tok(TigerSyms.TIMES);
            }
          case 72: break;
          case 11: 
            { return tok(TigerSyms.COLON);
            }
          case 73: break;
          case 12: 
            { return tok(TigerSyms.EQ);
            }
          case 74: break;
          case 13: 
            { return tok(TigerSyms.GT);
            }
          case 75: break;
          case 14: 
            { return tok(TigerSyms.COMMA);
            }
          case 76: break;
          case 15: 
            { return tok(TigerSyms.SEMICOLON);
            }
          case 77: break;
          case 16: 
            { return tok(TigerSyms.LPAREN);
            }
          case 78: break;
          case 17: 
            { return tok(TigerSyms.RPAREN);
            }
          case 79: break;
          case 18: 
            { return tok(TigerSyms.LBRACK);
            }
          case 80: break;
          case 19: 
            { return tok(TigerSyms.RBRACK);
            }
          case 81: break;
          case 20: 
            { return tok(TigerSyms.LBRACE);
            }
          case 82: break;
          case 21: 
            { return tok(TigerSyms.RBRACE);
            }
          case 83: break;
          case 22: 
            { return tok(TigerSyms.DOT);
            }
          case 84: break;
          case 23: 
            { return tok(TigerSyms.PLUS);
            }
          case 85: break;
          case 24: 
            { return tok(TigerSyms.AND);
            }
          case 86: break;
          case 25: 
            { return tok(TigerSyms.OR);
            }
          case 87: break;
          case 26: 
            { // Hack alert:  the success of this is totally dependent on the order of
    // its specification in the LEX file.  It should be the last matchable
    // regexp in COMMENT.
            }
          case 88: break;
          case 27: 
            { currentString = currentString.concat(yytext());
    // Ordinary letters, spaces, and digits
    charsReadForStr += yylength();
            }
          case 89: break;
          case 28: 
            { readingString = false;
  commentOrStringBegins = -1;  yybegin(YYINITIAL);
  return tok(TigerSyms.STRING, currentString);
            }
          case 90: break;
          case 29: 
            { err("String ended by newline character at line " + yyline);
            }
          case 91: break;
          case 30: 
            { return tok(TigerSyms.IN);
            }
          case 92: break;
          case 31: 
            { return tok(TigerSyms.IF);
            }
          case 93: break;
          case 32: 
            { return tok(TigerSyms.LE);
            }
          case 94: break;
          case 33: 
            { return tok(TigerSyms.NEQ);
            }
          case 95: break;
          case 34: 
            { if (commentDepth != 0) throw new IOException(
      "Internal error: bogus commentDepth value of " + commentDepth +
      " in state YYINITIAL, \n while scanning line " + yyline);
  // This is strictly for debugging purposes:  should never appear in real use
  // System.out.println("Beginning COMMENT...");
  commentOrStringBegins = yyline;
  commentDepth++;
  yybegin(COMMENT);
            }
          case 96: break;
          case 35: 
            { return tok(TigerSyms.OF);
            }
          case 97: break;
          case 36: 
            { return tok(TigerSyms.TO);
            }
          case 98: break;
          case 37: 
            { return tok(TigerSyms.DO);
            }
          case 99: break;
          case 38: 
            { return tok(TigerSyms.ASSIGN);
            }
          case 100: break;
          case 39: 
            { return tok(TigerSyms.GE);
            }
          case 101: break;
          case 40: 
            { commentDepth++;
            }
          case 102: break;
          case 41: 
            { //System.out.println("Possible close of comment...");
  if ((--commentDepth) == 0) {
   // System.out.println("...confirmed.  Resuming normal scan.");
    commentOrStringBegins = -1;
    yybegin(YYINITIAL);
  }
            }
          case 103: break;
          case 42: 
            { err("String contains illegal escape character at line " + yyline);
            }
          case 104: break;
          case 43: 
            { currentString = currentString.concat("\\\\");
    charsReadForStr += yylength();
            }
          case 105: break;
          case 44: 
            { currentString = currentString.concat("\\\"");
    charsReadForStr += yylength();
            }
          case 106: break;
          case 45: 
            { currentString = currentString.concat("\n");
    charsReadForStr += yylength();
            }
          case 107: break;
          case 46: 
            { currentString = currentString.concat("\t");
    charsReadForStr += yylength();
            }
          case 108: break;
          case 47: 
            { return tok(TigerSyms.LET);
            }
          case 109: break;
          case 48: 
            { return tok(TigerSyms.NIL);
            }
          case 110: break;
          case 49: 
            { return tok(TigerSyms.END);
            }
          case 111: break;
          case 50: 
            { return tok(TigerSyms.EOF);
            }
          case 112: break;
          case 51: 
            { return tok(TigerSyms.FOR);
            }
          case 113: break;
          case 52: 
            { return tok(TigerSyms.VAR);
            }
          case 114: break;
          case 53: 
            { // Line continuation -- ignore everything in between the backslashes
    newline();
    charsReadForStr += yylength();
            }
          case 115: break;
          case 54: 
            { return tok(TigerSyms.ELSE);
            }
          case 116: break;
          case 55: 
            { return tok(TigerSyms.THEN);
            }
          case 117: break;
          case 56: 
            { return tok(TigerSyms.TYPE);
            }
          case 118: break;
          case 57: 
            { return tok(TigerSyms.BREAK);
            }
          case 119: break;
          case 58: 
            { return tok(TigerSyms.ARRAY);
            }
          case 120: break;
          case 59: 
            { return tok(TigerSyms.WHILE);
            }
          case 121: break;
          case 60: 
            { //Character c = new Character(
		//     (char) (Integer.parseInt(yytext().substring(1)) % 256));
		     // Because Java uses Unicode, and we only want to support
		     // extended ASCII
    //currentString = currentString.concat(c.toString());
    int c = Integer.parseInt(yytext().substring(1)) % 256;
    currentString = currentString.concat("\\" + c + " ");
    charsReadForStr += yylength();
            }
          case 122: break;
          case 61: 
            { return tok(TigerSyms.IMPORT);
            }
          case 123: break;
          case 62: 
            { return tok(TigerSyms.FUNCTION);
            }
          case 124: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
