
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Apr 22 19:05:54 EDT 2020
//----------------------------------------------------

package tigerc.syntax.parse;

/** CUP generated interface containing symbol constants. */
public interface TigerSyms {
  /* terminals */
  public static final int DIVIDE = 19;
  public static final int FUNCTION = 43;
  public static final int GE = 25;
  public static final int UMINUS = 46;
  public static final int LPAREN = 9;
  public static final int INT = 4;
  public static final int ARRAY = 29;
  public static final int FOR = 34;
  public static final int MINUS = 17;
  public static final int RPAREN = 10;
  public static final int SEMICOLON = 8;
  public static final int AND = 26;
  public static final int LT = 22;
  public static final int TYPE = 45;
  public static final int NIL = 42;
  public static final int IN = 38;
  public static final int OR = 27;
  public static final int COMMA = 6;
  public static final int PLUS = 16;
  public static final int ASSIGN = 28;
  public static final int IF = 30;
  public static final int DOT = 15;
  public static final int ID = 2;
  public static final int LE = 23;
  public static final int OF = 40;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int NEQ = 21;
  public static final int BREAK = 41;
  public static final int EQ = 20;
  public static final int LBRACK = 11;
  public static final int IMPORT = 5;
  public static final int TIMES = 18;
  public static final int COLON = 7;
  public static final int LBRACE = 13;
  public static final int ELSE = 32;
  public static final int RBRACK = 12;
  public static final int TO = 35;
  public static final int WHILE = 33;
  public static final int LET = 37;
  public static final int THEN = 31;
  public static final int RBRACE = 14;
  public static final int END = 39;
  public static final int STRING = 3;
  public static final int GT = 24;
  public static final int VAR = 44;
  public static final int DO = 36;
}

